## Подготовка окружения

In [1]:
!pip install opencv-python

In [2]:
import cv2
import numpy as np

## Задание №1

Найти ближайшую ортогональную матрицу (в смысле нормы
Фробениуса) к матрице $A$. Вывести результат в консоль и, посмотрев на него, найти соответствующие этому преобразованию угол и направление поворота.

**Решение.** Для нахождения ближайшей ортогональной матрицы воспользуемся доказанным на лекции равенством:

>$
 \operatorname{arg\,min}_{BB^T=E} ||A-B||_F = UV^T
$

In [3]:
A = [[0.5,        2.16506351, 0.4330127],
     [-0.8660254, 1.25,       0.25     ],
     [0,          0.5,        2.5      ]]
     
A = np.array(A)

In [4]:
 d, u, vt = cv2.SVDecomp(A)

In [5]:
nom_A = np.matmul(u, vt)
print(nom_A)

[[ 5.00000000e-01  8.66025404e-01 -3.87999696e-10]
 [-8.66025404e-01  5.00000000e-01  1.65509423e-11]
 [ 2.08333333e-10  3.27741947e-10  1.00000000e+00]]


In [6]:
np.linalg.norm(A - nom_A)

2.2360679774464374

**Проверка**. Получившуюся матрицу с некоторой погрешностью можно считать единичной, следовательно `nom_A` ортогональная.

In [7]:
np.matmul(nom_A.transpose(), nom_A)

array([[ 1.00000000e+00,  6.99369424e-17, -5.15817108e-17],
       [ 6.99369424e-17,  1.00000000e+00, -1.75180098e-16],
       [-5.15817108e-17, -1.75180098e-16,  1.00000000e+00]])

**Угол и направление поворота.** Если внимательно посмотреть на матрицу, то можно заметить, что она соответствует матрице поворота вокруг оси $z$ на угол $-60^o$.

In [8]:
np.rad2deg(np.arcsin(-0.866025404))

-60.00000002470152

## Задание №2

При помощи SVD найти обратную матрицу к квадратной матрице nxn для размеров матрицы n=3 и n=10.

Матрица состоит из элементов:
>$A_{i,j} = \frac{1}{i+j-1}$

Для избежания деления на ноль, индексация элементов матрицы начинается с единицы.

**Решение.** 
>$A^{−1} = (UDV^T)^{-1} = VD^{−1}U^T$

In [9]:
for n in [3, 10]:
  A = np.fromfunction(lambda i, j: 1 / ( (i + 1) + (j + 1) - 1), (n,n))
  print("\nMatrix:\n{}\n".format(A))
  d, u, vt = cv2.SVDecomp(A)

  v = vt.transpose()
  ut = u.transpose()
  inv_d = np.diag(1 / d.flatten())
  
  inv_a = v.dot(inv_d).dot(ut)
  print("\nInverse matrix:\n{}\n".format(A))
  print("\nThe next matrix must be identity matrix:\n{}\n".format(inv_a.dot(A)))


Matrix:
[[1.         0.5        0.33333333]
 [0.5        0.33333333 0.25      ]
 [0.33333333 0.25       0.2       ]]


Inverse matrix:
[[1.         0.5        0.33333333]
 [0.5        0.33333333 0.25      ]
 [0.33333333 0.25       0.2       ]]


The next matrix must be identity matrix:
[[ 1.00000000e+00  0.00000000e+00  1.55431223e-16]
 [ 5.69914486e-15  1.00000000e+00  8.43769499e-16]
 [-1.99099996e-14 -7.10542736e-15  1.00000000e+00]]


Matrix:
[[1.         0.5        0.33333333 0.25       0.2        0.16666667
  0.14285714 0.125      0.11111111 0.1       ]
 [0.5        0.33333333 0.25       0.2        0.16666667 0.14285714
  0.125      0.11111111 0.1        0.09090909]
 [0.33333333 0.25       0.2        0.16666667 0.14285714 0.125
  0.11111111 0.1        0.09090909 0.08333333]
 [0.25       0.2        0.16666667 0.14285714 0.125      0.11111111
  0.1        0.09090909 0.08333333 0.07692308]
 [0.2        0.16666667 0.14285714 0.125      0.11111111 0.1
  0.09090909 0.08333333 0.076923

## Задание №3

Для квадратной матрицы nxn найти с использованием SVD все решения уравнений $AX=0$ для $n=4$

Матрица состоит из элементов:
>$A_{i,j} = i+j-1$

**Решение.** Вектор x, решение системы, можно охарактеризовать как правый сингулярный вектор, соответствующий сингулярному значению матрицы A, равному нулю. Будем принимать элемент равным нулю, если он по модулю меньше $1e-10$.

In [10]:
A = np.fromfunction(lambda i, j: ( (i + 1) + (j + 1) - 1), (4,4))
print("\nMatrix:\n{}\n".format(A))
d, u, vt = cv2.SVDecomp(A)

x_len = len(np.where(np.abs(d) < 1e-10))
x_arr = vt[-x_len:]

for i in range(x_len):
  print("Solution #{}:\n{}\n".format(i + 1, x_arr[i]))
  test = A.dot(x_arr[i])
  test[test < 1e-10] = 0
  print("The next values must be ZERO: {}\n\n".format(test))


Matrix:
[[1. 2. 3. 4.]
 [2. 3. 4. 5.]
 [3. 4. 5. 6.]
 [4. 5. 6. 7.]]

Solution #1:
[ 0.46874253 -0.83617774  0.2661279   0.10130732]

The next values must be ZERO: [0. 0. 0. 0.]


Solution #2:
[ 0.28333804 -0.028404   -0.79320612  0.53827208]

The next values must be ZERO: [0. 0. 0. 0.]




## Задание №4

Написать программу, находящую все точки пересечения двух прямых на
плоскости методом однородных координат. Прямые заданы уравнениями:
>$ax+by+c=0$

>$cx+dy+e=0$

**Решение.**
Точка пересечения двух линий, заданных как $l_1,l_2$, есть их векторное произведение:
>$p=l_1 * l_2$

In [11]:
l1 = np.random.rand(3) * 10
l2 = np.random.rand(3) * 10

p = np.cross(l1, l2)

if np.abs(p[2]) < 1e-10:
  print("Lines {} and {} are parallel".format(l1, l2))
else:
  h_p = [p[0]/p[2], p[1]/p[2], 1]
  print("Intersection point of {} and {}:\t{}".format(l1, l2, h_p[:2]))
  print("The next values must be equal to or close to ZERO: {}\n\n".format([l1.dot(h_p), l2.dot(h_p)]))

Intersection point of [7.63372134 9.25650559 5.37516423] and [7.68407199 6.5340733  6.45949679]:	[-1.1610613921638964, 0.37682199373324476]
The next values must be equal to or close to ZERO: [-3.552713678800501e-15, -2.6645352591003757e-15]


